/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestAPIImport } from './routes/testAPI'
import { Route as WildernautIndexImport } from './routes/wildernaut/index'
import { Route as WilderkindIndexImport } from './routes/wilderkind/index'
import { Route as WilderkindIdImport } from './routes/wilderkind/$id'
import { Route as WildernautIdIndexImport } from './routes/wildernaut/$id/index'
import { Route as WildernautIdCollectionImport } from './routes/wildernaut/$id/collection'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const TestAPIRoute = TestAPIImport.update({
  path: '/testAPI',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const WildernautIndexRoute = WildernautIndexImport.update({
  path: '/wildernaut/',
  getParentRoute: () => rootRoute,
} as any)

const WilderkindIndexRoute = WilderkindIndexImport.update({
  path: '/wilderkind/',
  getParentRoute: () => rootRoute,
} as any)

const WilderkindIdRoute = WilderkindIdImport.update({
  path: '/wilderkind/$id',
  getParentRoute: () => rootRoute,
} as any)

const WildernautIdIndexRoute = WildernautIdIndexImport.update({
  path: '/wildernaut/$id/',
  getParentRoute: () => rootRoute,
} as any)

const WildernautIdCollectionRoute = WildernautIdCollectionImport.update({
  path: '/wildernaut/$id/collection',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/testAPI': {
      id: '/testAPI'
      path: '/testAPI'
      fullPath: '/testAPI'
      preLoaderRoute: typeof TestAPIImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/wilderkind/$id': {
      id: '/wilderkind/$id'
      path: '/wilderkind/$id'
      fullPath: '/wilderkind/$id'
      preLoaderRoute: typeof WilderkindIdImport
      parentRoute: typeof rootRoute
    }
    '/wilderkind/': {
      id: '/wilderkind/'
      path: '/wilderkind'
      fullPath: '/wilderkind'
      preLoaderRoute: typeof WilderkindIndexImport
      parentRoute: typeof rootRoute
    }
    '/wildernaut/': {
      id: '/wildernaut/'
      path: '/wildernaut'
      fullPath: '/wildernaut'
      preLoaderRoute: typeof WildernautIndexImport
      parentRoute: typeof rootRoute
    }
    '/wildernaut/$id/collection': {
      id: '/wildernaut/$id/collection'
      path: '/wildernaut/$id/collection'
      fullPath: '/wildernaut/$id/collection'
      preLoaderRoute: typeof WildernautIdCollectionImport
      parentRoute: typeof rootRoute
    }
    '/wildernaut/$id/': {
      id: '/wildernaut/$id/'
      path: '/wildernaut/$id'
      fullPath: '/wildernaut/$id'
      preLoaderRoute: typeof WildernautIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  TestAPIRoute,
  AboutLazyRoute,
  WilderkindIdRoute,
  WilderkindIndexRoute,
  WildernautIndexRoute,
  WildernautIdCollectionRoute,
  WildernautIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/testAPI",
        "/about",
        "/wilderkind/$id",
        "/wilderkind/",
        "/wildernaut/",
        "/wildernaut/$id/collection",
        "/wildernaut/$id/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/testAPI": {
      "filePath": "testAPI.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/wilderkind/$id": {
      "filePath": "wilderkind/$id.tsx"
    },
    "/wilderkind/": {
      "filePath": "wilderkind/index.tsx"
    },
    "/wildernaut/": {
      "filePath": "wildernaut/index.tsx"
    },
    "/wildernaut/$id/collection": {
      "filePath": "wildernaut/$id/collection.tsx"
    },
    "/wildernaut/$id/": {
      "filePath": "wildernaut/$id/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
